version: '3.4'

services:
  aggregator:
    image: aggregator:v2
    ports:
      - "9897:80"
    depends_on:
      - jaggerservice
      - ordermanagement
      - usermanagement
    networks:
      - backend

  ordermanagement:
    image: orderservice:v2
    ports:
      - "9898:80"
    depends_on:
      - jaggerservice
    networks:
      - backend


  usermanagement:
    image: userservice:v2
    ports:
      - "9899:80"
    depends_on:
      - jaggerservice
    networks:
      - backend

  jaggerservice:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411 
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks: 
      - backend

networks:
    backend:
      driver: bridge

